version: 2
updates:
  - package-ecosystem: "bun"
    directory: "/frontend"
    groups:
      minor-patch:
        update-types:
          - "patch"
          - "minor"
    schedule:
      interval: "daily"

  - package-ecosystem: "gomod"
    directory: "/"
    groups:
      minor-patch:
        update-types:
          - "patch"
          - "minor"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
