FROM golang:1.25-alpine3.21

WORKDIR /tinyauth

COPY go.mod ./
COPY go.sum ./

RUN go mod download

RUN go install github.com/air-verse/air@v1.61.7
RUN go install github.com/go-delve/delve/cmd/dlv@latest

COPY ./cmd ./cmd
COPY ./internal ./internal
COPY ./air.toml ./

EXPOSE 3000

ENV DATABASEPATH=/data/tinyauth.db

ENV RESOURCESDIR=/data/resources

ENTRYPOINT ["air", "-c", "air.toml"]