FROM oven/bun:1.1.45-alpine

WORKDIR /site

COPY ./site/package.json ./
COPY ./site/bun.lockb ./

RUN bun install

COPY ./site/public ./public
COPY ./site/src ./src

COPY ./site/eslint.config.js ./
COPY ./site/index.html ./
COPY ./site/tsconfig.json ./
COPY ./site/tsconfig.app.json ./
COPY ./site/tsconfig.node.json ./
COPY ./site/vite.config.ts ./
COPY ./site/postcss.config.cjs ./

EXPOSE 5173

ENTRYPOINT ["bun", "run", "dev"]