// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

type Session struct {
	UUID        string
	Username    string
	Email       string
	Name        string
	Provider    string
	TotpPending bool
	OAuthGroups string
	Expiry      int64
	OAuthName   string
}
