// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: oidc_queries.sql

package repository

import (
	"context"
)

const createOidcCode = `-- name: CreateOidcCode :one
INSERT INTO "oidc_codes" (
    "sub",
    "code",
    "scope",
    "redirect_uri",
    "client_id",
    "expires_at"
) VALUES (
    ?, ?, ?, ?, ?, ?
)
RETURNING sub, code, scope, redirect_uri, client_id, expires_at
`

type CreateOidcCodeParams struct {
	Sub         string
	Code        string
	Scope       string
	RedirectURI string
	ClientID    string
	ExpiresAt   int64
}

func (q *Queries) CreateOidcCode(ctx context.Context, arg CreateOidcCodeParams) (OidcCode, error) {
	row := q.db.QueryRowContext(ctx, createOidcCode,
		arg.Sub,
		arg.Code,
		arg.Scope,
		arg.RedirectURI,
		arg.ClientID,
		arg.ExpiresAt,
	)
	var i OidcCode
	err := row.Scan(
		&i.Sub,
		&i.Code,
		&i.Scope,
		&i.RedirectURI,
		&i.ClientID,
		&i.ExpiresAt,
	)
	return i, err
}

const createOidcToken = `-- name: CreateOidcToken :one
INSERT INTO "oidc_tokens" (
    "sub",
    "access_token",
    "scope",
    "client_id",
    "expires_at"
) VALUES (
    ?, ?, ?, ?, ?
)
RETURNING sub, access_token, scope, client_id, expires_at
`

type CreateOidcTokenParams struct {
	Sub         string
	AccessToken string
	Scope       string
	ClientID    string
	ExpiresAt   int64
}

func (q *Queries) CreateOidcToken(ctx context.Context, arg CreateOidcTokenParams) (OidcToken, error) {
	row := q.db.QueryRowContext(ctx, createOidcToken,
		arg.Sub,
		arg.AccessToken,
		arg.Scope,
		arg.ClientID,
		arg.ExpiresAt,
	)
	var i OidcToken
	err := row.Scan(
		&i.Sub,
		&i.AccessToken,
		&i.Scope,
		&i.ClientID,
		&i.ExpiresAt,
	)
	return i, err
}

const createOidcUserInfo = `-- name: CreateOidcUserInfo :one
INSERT INTO "oidc_userinfo" (
    "sub",
    "name",
    "preferred_username",
    "email",
    "groups",
    "updated_at"
) VALUES (
    ?, ?, ?, ?, ?, ?
)
RETURNING sub, name, preferred_username, email, "groups", updated_at
`

type CreateOidcUserInfoParams struct {
	Sub               string
	Name              string
	PreferredUsername string
	Email             string
	Groups            string
	UpdatedAt         int64
}

func (q *Queries) CreateOidcUserInfo(ctx context.Context, arg CreateOidcUserInfoParams) (OidcUserinfo, error) {
	row := q.db.QueryRowContext(ctx, createOidcUserInfo,
		arg.Sub,
		arg.Name,
		arg.PreferredUsername,
		arg.Email,
		arg.Groups,
		arg.UpdatedAt,
	)
	var i OidcUserinfo
	err := row.Scan(
		&i.Sub,
		&i.Name,
		&i.PreferredUsername,
		&i.Email,
		&i.Groups,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteOidcCode = `-- name: DeleteOidcCode :exec
DELETE FROM "oidc_codes"
WHERE "code" = ?
`

func (q *Queries) DeleteOidcCode(ctx context.Context, code string) error {
	_, err := q.db.ExecContext(ctx, deleteOidcCode, code)
	return err
}

const deleteOidcToken = `-- name: DeleteOidcToken :exec
DELETE FROM "oidc_tokens"
WHERE "access_token" = ?
`

func (q *Queries) DeleteOidcToken(ctx context.Context, accessToken string) error {
	_, err := q.db.ExecContext(ctx, deleteOidcToken, accessToken)
	return err
}

const deleteOidcUserInfo = `-- name: DeleteOidcUserInfo :exec
DELETE FROM "oidc_userinfo"
WHERE "sub" = ?
`

func (q *Queries) DeleteOidcUserInfo(ctx context.Context, sub string) error {
	_, err := q.db.ExecContext(ctx, deleteOidcUserInfo, sub)
	return err
}

const getOidcCode = `-- name: GetOidcCode :one
SELECT sub, code, scope, redirect_uri, client_id, expires_at FROM "oidc_codes"
WHERE "code" = ?
`

func (q *Queries) GetOidcCode(ctx context.Context, code string) (OidcCode, error) {
	row := q.db.QueryRowContext(ctx, getOidcCode, code)
	var i OidcCode
	err := row.Scan(
		&i.Sub,
		&i.Code,
		&i.Scope,
		&i.RedirectURI,
		&i.ClientID,
		&i.ExpiresAt,
	)
	return i, err
}

const getOidcToken = `-- name: GetOidcToken :one
SELECT sub, access_token, scope, client_id, expires_at FROM "oidc_tokens"
WHERE "access_token" = ?
`

func (q *Queries) GetOidcToken(ctx context.Context, accessToken string) (OidcToken, error) {
	row := q.db.QueryRowContext(ctx, getOidcToken, accessToken)
	var i OidcToken
	err := row.Scan(
		&i.Sub,
		&i.AccessToken,
		&i.Scope,
		&i.ClientID,
		&i.ExpiresAt,
	)
	return i, err
}

const getOidcUserInfo = `-- name: GetOidcUserInfo :one
SELECT sub, name, preferred_username, email, "groups", updated_at FROM "oidc_userinfo"
WHERE "sub" = ?
`

func (q *Queries) GetOidcUserInfo(ctx context.Context, sub string) (OidcUserinfo, error) {
	row := q.db.QueryRowContext(ctx, getOidcUserInfo, sub)
	var i OidcUserinfo
	err := row.Scan(
		&i.Sub,
		&i.Name,
		&i.PreferredUsername,
		&i.Email,
		&i.Groups,
		&i.UpdatedAt,
	)
	return i, err
}
